@echo off
cd /d "%~dp0"
echo Deleting old virtual environment...
rmdir /s /q venv
echo Creating new virtual environment...
python -m venv venv
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing dependencies from requirements.txt...
pip install -r requirements.txt
echo Virtual environment reinstallation complete.
pause
